### ISSUE TITLE
Random image

### ISSUE THREAD

**Issue by darekkay** [darekkay/dashboard#10]
The current Image widget requires the user to type in the full URL of an image:

![image](https://user-images.githubusercontent.com/3101914/94661627-9be40b00-0307-11eb-9042-5e6682338920.png)

It would be great to have a "Random image" button, so a) the user can see how the widget is supposed to work and b) getting a random image is a nice feature in itself.

Something like the [Unsplash API](https://unsplash.com/developers) could be used.

There are some related ideas for images to be considered when working on this:
 - Upload a custom image instead of having to type a URL
 - Have a random daily image - this can be either a standalone widget or made part of the existing Image widget

**Comment by syentix** [comment]
Hey! I would try and add the Unsplash random picture if you wouldn't mind. Have you considered tagging your issues with hacktoberfest?

**Comment by darekkay** [comment]
Hey @syentix , I didn't opt-in into Hacktoberfest because of the initial spam wave. But I am more than happy marking PRs as `hacktoberfest-accepted` (which will also count towards the 4 PR target) for valid PRs. I also didn't mark the issues with `hacktoberfest` (as well as `up-for-grabs`), because `good first issue` should cover it as well.

Regarding this issue, feel free to connect with @adrianrios25 who [mentioned](https://github.com/darekkay/dashboard/issues/13#issuecomment-704927063) his interest in working on a standalone random image widget. Both features could probably use the same internal server endpoint for getting a random Unsplash image.

**Comment by adrianrios25** [comment]
hello @darekkay , I'm done with creating the api/server side for getting random image using unsplash api. Let me know if that is okay, but unfortunately I can't continue the front-end side(app) of the standalone widget. @syentix you can work on this if you like. If my pull request will not be accepted, I will share the server side code to you via email.

**Comment by syentix** [comment]
No that sounds good, I'll wait it out then

**Comment by darekkay** [comment]
@syentix The PR is now merged, so the `/unsplash/random` route is available. To use it, you'll need to create an Unsplash account and create a developer application, see [documentation](https://unsplash.com/documentation). The API key ("Access key") must be part of `server/.env` (which is your local, git-ignored env file) or any other dotenv-supported local file:

```
API_UNSPLASH=...
```

There are also some [Unsplash guidelines](https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines) that we have to follow, especially:

> When displaying a photo from Unsplash, your application must attribute Unsplash, the Unsplash photographer, and contain a link back to their Unsplash profile. All links back to Unsplash should use utm parameters in the ?utm_source=your_app_name&utm_medium=referral.

Additionally, only 50 requests/hour can be done on an unreviewed Unsplash App. I would file a request to review this project to get to the 5000 requests/hours limit.

As promised on gitter, I will improve the documentation regarding the server module soon.

**Comment by adrianrios25** [comment]
hello @darekkay , can I request to tag my PR as hacktoberfest-accepted? thanks! this is really great experience :)

**Comment by syentix** [comment]
This can be closed, right?

**Comment by darekkay** [comment]
We've got a random image _widget_ now, yes. But this task was more about somehow improving the existing _image_ widget to provide a URL example. But yeah, it's so low priority that we can as well close it.
