### ISSUE TITLE
New widgets (placeholder)

### ISSUE THREAD

**Issue by darekkay** [darekkay/dashboard#13]
There are many [widget ideas](https://dashboard.darekkay.com/docs/roadmap/#widget-ideas) for the Dashboard. This task is a placeholder for people to find a new widget they would like to work on.

**Comment by adrianrios25** [comment]
hello @darekkay , can I work for the Random Image as stand alone widget?

**Comment by darekkay** [comment]
Sure @adrianrios25 🚀

**Comment by syentix** [comment]
@adrianrios25 hey I was about to work on the same/similar widget. If you need any help tell me how to get in contact and we could work on it together.

**Comment by adrianrios25** [comment]
hi @darekkay 
I created a youtube stats widget

![image](https://user-images.githubusercontent.com/12592624/96141653-cc48bd80-0f33-11eb-870b-aab7922251d8.png)

**Comment by adrianrios25** [comment]
what do you think? if I send a pull request, should I include both server and client side in one request? or should I separate it?

**Comment by darekkay** [comment]
Thanks @adrianrios25 , it looks good 🚀  One PR for both client & server is fine

**Comment by adrianrios25** [comment]
@darekkay , I created a PR for the youtube stats.

**Comment by adrianrios25** [comment]
Hello @darekkay , 
I found this inspirational quote api while browsing some repos, I think this can be a good widget, we can create a random inspirational quote. https://github.com/vinitshahdeo/inspirational-quotes

what do you think?

**Comment by darekkay** [comment]
@adrianrios25  I've also found this quotes project a few weeks ago and was thinking the same, so sure! 🚀

**Comment by peeyushsrj** [comment]
Hey @darekkay 

I have two great ideas aboutthis.
1. Simple Integration of API ( So each widget would request to url provided at the creation time of widget)

This is to support the small cases, where most people need to do  perform GET request. THus will cover lot of scenarios! 

2. Integration of webhook

Basically people use webhook to get the latest blog post, build status etc. So thinking of generalised panel for this, given it should be cachable. If it's okay for you , iwould try to add. But i am not expert on front-end side (espcially react)

**Comment by darekkay** [comment]
Hey @peeyushsrj , thank you for your ideas!

> Simple Integration of API ( So each widget would request to url provided at the creation time of widget)

Currently, there are two file generators: 

- Run `yarn generate` (or `npm run generate`) in the `app` module to create a widget boilerplate. Select `yes` at the `Does your widget use sagas (e.g. fetch external data)?` prompt, and a `sagas.js` file will be created with some data-fetching code.

- Run `yarn generate` in the `server` module to create a server route.

There's probably some more room to improve the boilerplate code, but for me it has been good enough. I'm open to improvements, though 🙂 

> Integration of webhook

I've created #25

**Comment by darekkay** [comment]
I've enabled [Discussions](https://github.com/darekkay/dashboard/discussions) in this repository, so this placeholder issue is no longer needed.
