### ISSUE TITLE
GitHub Stats are missing when the value is zero

### ISSUE THREAD

**Issue by darekkay** [darekkay/dashboard#15]
Instead of the row now being rendered at all, a `0` value should be displayed:

![image](https://user-images.githubusercontent.com/3101914/94782535-a8ca3280-03cb-11eb-8a4c-b3d1686662bb.png)

The reason is the [usage](https://github.com/darekkay/dashboard/blob/master/app/src/widgets/github-stats/index.tsx#L51) of `!!` which is meant for missing values, but it handles `0` as well.

Please notice, there's a general issue of handling data while it's not available. Currently, nothing will be rendered at all when the data is being fetched, but some indicator would probably be good (can be handled in a separate issue).

**Comment by TateKennington** [comment]
Hi, I'm interested in having a look at this issue, could you assign it to me?

**Comment by darekkay** [comment]
Sure, thanks! 🚀
