### ISSUE TITLE
Find a channel to exchange

### ISSUE THREAD

**Issue by faboo03** [darekkay/dashboard#3]
Hello, 

I made a quick overview of the tools that I knew (or not :)) used in big open source project. 

I believe that I would go like this : 
* Gitter to chat simply : No archive, no file sharing etc ...  
* Slack if we need to go further :) 

For the project, I guess we could just use a Github Project and make some card for extension. ;)

So let's try with gitter and start to know each other ;)

**Comment by darekkay** [comment]
I've created a [Gitter community](https://gitter.im/darekkay-dashboard/community) for the project communication :)
